In [1]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-04,ETE Hortolandia - 18 multas Cetesb em dez meses,4,infraestrutura_urbana,IU_01,indireta,alerta,ETE de Hortolandia acumulou 18 multas da Cetes...,Hortolandia,Hortolandia,local,indicador,Sabesp preve R$ 28 mi para modernizacao e estu...,nao_aplicavel,nao_aplicavel,negativo,saneamento
1,Tribuna Liberal,2026-03-04,Pai sequestra filha de 2 anos - Jardim Amanda,9,capital_humano,NaN,contextual,alerta,Pai sequestra filha de 2 anos no Jardim Amanda...,Hortolandia,Hortolandia,local,problema,Evento iniciou na Rua Washington Luiz no Jardi...,351,alto,negativo,seguranca
2,Tribuna Liberal,2026-03-04,Regularizacao fundiaria e habitacao - reuniao ...,8,infraestrutura_urbana,IU_01,indireta,media,Prefeito reune-se com secretario estadual de H...,Hortolandia,Hortolandia,local,politica_publica,Bairros envolvidos: Jd. Aline Santiago Guedes ...,nao_aplicavel,nao_aplicavel,positivo,habitacao
3,Tribuna Liberal,2026-03-04,Obra de drenagem - Jardim Novo Angulo,8,infraestrutura_urbana,IU_01,indireta,media,Maquinas iniciam obras de reparo de erosao na ...,Hortolandia,Hortolandia,local,politica_publica,Obra executada como contrapartida de empreendi...,307,medio,positivo,infraestrutura
4,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,4,renda_trabalho,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,Hortolandia,local,problema,Mobilizacao apos suspensao da cesta de Natal; ...,nao_aplicavel,nao_aplicavel,negativo,economia

In [2]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-03,Viaduto Vila Real - rotatoria comeca proxima s...,7,infraestrutura_urbana,IU_03,indireta,media,Prefeitura recebe documentacao do projeto da r...,Hortolandia,Hortolandia,local,politica_publica,Conecta Av. Santana Jd. Amanda ao Centro e Nov...,nao_aplicavel,nao_aplicavel,positivo,mobilidade
1,Tribuna Liberal,2026-03-03,Mpox - caso confirmado em Hortolandia,5,capital_humano,NaN,indireta,media,Hortolandia figura entre municipios com casos ...,Hortolandia,Hortolandia,regional,indicador,Hortolandia Paulinia e Americana integram list...,nao_aplicavel,nao_aplicavel,negativo,saude
2,Tribuna Liberal,2026-03-03,Mes da Mulher - evento para 200 servidoras no ...,7,capital_humano,NaN,indireta,baixa,Prefeitura reune 200 servidoras na abertura do...,Hortolandia,Hortolandia,local,politica_publica,Organizado pelo Departamento das Mulheres; dir...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social
3,Tribuna Liberal,2026-03-03,Carro invade Escola Estadual Maria Rita Araujo...,10,capital_humano,CH_03,contextual,alta,Carro invade Escola Estadual no Parque Terras ...,Hortolandia,Hortolandia,local,problema,Veiculo registrado em nome de terceiro; ocupan...,383,medio,negativo,transito
4,Tribuna Liberal,2026-03-03,ETE Hortolandia - charge sobre bloqueadores de ar,1,infraestrutura_urbana,NaN,contextual,media,Charge de capa faz referencia a odores da ETE ...,Hortolandia,Hortolandia,local,problema,Charge sugere que Monte Mor autorizou bloquead...,nao_aplicavel,nao_aplicavel,negativo,saneamento

In [3]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-04,ETE Hortolandia - 18 multas Cetesb em dez meses,4,infraestrutura_urbana,IU_01,indireta,alerta,ETE de Hortolandia acumulou 18 multas da Cetes...,Hortolandia,Hortolandia,local,indicador,Sabesp preve R$ 28 mi para modernizacao e estu...,nao_aplicavel,nao_aplicavel,negativo,saneamento
1,Tribuna Liberal,2026-03-04,Pai sequestra filha de 2 anos - Jardim Amanda,9,capital_humano,NaN,contextual,alerta,Pai sequestra filha de 2 anos no Jardim Amanda...,Hortolandia,Hortolandia,local,problema,Evento iniciou na Rua Washington Luiz no Jardi...,351,alto,negativo,seguranca
2,Tribuna Liberal,2026-03-04,Regularizacao fundiaria e habitacao - reuniao ...,8,infraestrutura_urbana,IU_01,indireta,media,Prefeito reune-se com secretario estadual de H...,Hortolandia,Hortolandia,local,politica_publica,Bairros envolvidos: Jd. Aline Santiago Guedes ...,nao_aplicavel,nao_aplicavel,positivo,habitacao
3,Tribuna Liberal,2026-03-04,Obra de drenagem - Jardim Novo Angulo,8,infraestrutura_urbana,IU_01,indireta,media,Maquinas iniciam obras de reparo de erosao na ...,Hortolandia,Hortolandia,local,politica_publica,Obra executada como contrapartida de empreendi...,307,medio,positivo,infraestrutura
4,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,4,renda_trabalho,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,Hortolandia,local,problema,Mobilizacao apos suspensao da cesta de Natal; ...,nao_aplicavel,nao_aplicavel,negativo,economia

In [4]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

  fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento
0  Tribuna Liberal\t2026-03-05\tMCMV - 400 unidad...
1  Tribuna Liberal\t2026-03-05\tBriga com dois ba...
2  Tribuna Liberal\t2026-03-05\tPainel violencia ...
3  Tribuna Liberal\t2026-03-05\tInterdicao de pon...
4  Tribuna Liberal\t2026-03-05\tVisita do prefeit...

In [5]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

  fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento
0  Tribuna Liberal\t2026-03-06\tAuxilio-refeicao ...
1  Tribuna Liberal\t2026-03-06\tMCMV - 576 docume...
2  Tribuna Liberal\t2026-03-06\tFatec Hortolandia...
3  Tribuna Liberal\t2026-03-06\tPrisao preventiva...

In [6]:
import pandas as pd

arquivos = [
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv"
]

dfs = [pd.read_csv(f) for f in arquivos]

df_total = pd.concat(dfs, ignore_index=True)

df_total.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,9.0,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,93,alto,negativo,infraestrutura,NaN
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,9.0,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,86,alto,negativo,infraestrutura,NaN
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,9.0,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,333,alto,negativo,infraestrutura,NaN
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,9.0,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,317,alto,negativo,infraestrutura,NaN
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,6.0,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,Sem limite de vagas - funciona como Banco de T...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social,NaN

O r significa: “não interprete as barras como código” e simples e tab funicona "C:/Users/ailto/Atlas-Social-de-Hortolandia/00_governanca/series_jornalisticas/2026_03_01_tribuna_liberal.csv"                                                                          
📍 O que é ignore_index=True

Quando você usa:

df_total = pd.concat(dfs, ignore_index=True)

você está dizendo ao pandas:

“Ignore os índices originais de cada DataFrame e crie um novo índice contínuo.”

🧠 Vamos entender com calma
🔹 Cada CSV tem seu próprio índice

Quando você lê um arquivo:

df = pd.read_csv(...)

ele vem assim:

0
1
2
3

Agora imagine que você tem 5 arquivos.

Cada um deles começa do zero:

Arquivo 1 → 0,1,2,3
Arquivo 2 → 0,1,2
Arquivo 3 → 0,1,2,3,4
🔴 Se você NÃO usar ignore_index
df_total = pd.concat(dfs)

Resultado:

0
1
2
3
0
1
2
0
1
2
3
4

👉 Índices repetidos
👉 Bagunça lógica
👉 Pode dar erro em análises futuras

🟢 Se você usar ignore_index=True
df_total = pd.concat(dfs, ignore_index=True)

Resultado:

0
1
2
3
4
5
6
7
8
9
10
...

👉 índice único
👉 contínuo
👉 limpo para análise

📊 Interpretação conceitual (importante para o seu projeto)

No seu caso:

Você está criando um dataset consolidado de notícias.

Então faz total sentido dizer:

“Cada linha agora é um evento único no tempo — não importa de qual arquivo veio.”

Logo:

✔️ índice novo = identidade do dataset consolidado
❌ índice antigo = identidade do arquivo original (não interessa mais)

⚠️ Quando NÃO usar ignore_index

Você NÃO usaria se:

o índice tem significado (ex: ID único)
você quer rastrear origem linha a linha pelo índice

Mas no seu caso:

👉 você já tem:

data
fonte
item

Então o índice não tem valor analítico.

🧭 Tradução prática
Situação	Usar ignore_index
Juntar vários CSVs iguais	✅ Sim
Criar base única de análise	✅ Sim
Índice tem significado (ID)	❌ Não
📌 Em uma frase

ignore_index=True transforma vários arquivos separados em uma única tabela contínua e coerente para análise.

In [7]:
import pandas as pd
import glob

pasta = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

arquivos = glob.glob(pasta + r"\2026_*_*_tribuna_liberal.csv")

arquivos

['C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_04_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_06_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_07_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_08_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_10_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_12_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_14_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_18_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_21_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_24_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_25_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_26_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_27_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_28_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_29_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_31_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_02_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_07_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_08_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_09_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_10_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_11_tribuna_liberal.csv']

In [8]:
for f in arquivos:
    try:
        df = pd.read_csv(f)
        print(f, "->", list(df.columns))
    except Exception as e:
        print(f, "-> ERRO:", e)

C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv -> ['fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv -> ['fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_07_tribuna_liberal.csv -> ['fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_08_tribuna_liberal.csv -> ['data_publicacao\ttitulo_evento\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tresumo_evento\tlocalidade\ttipo_evento\tnivel_criticidade\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_10_tribuna_liberal.csv -> ['fonte\t"data"\t"item"\t"pagina"\t"dimensao_ivs"\t"codigo_variavel"\t"tipo_relacao_variavel"\t"nivel_criticidade"\t"resumo"\t"origem"\t"municipio_impactado"\t"tipo_abrangencia"\t"tipo_evento"\t"observacao"\t"cod_loteamento"\t"nivel_confianca_loteamento"\t"polaridade_evento"\t"tipo_origem_evento"']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_12_tribuna_liberal.csv -> ['fonte\t"data"\t"item"\t"pagina"\t"dimensao_ivs"\t"codigo_variavel"\t"tipo_relacao_variavel"\t"nivel_criticidade"\t"resumo"\t"origem"\t"municipio_impactado"\t"tipo_abrangencia"\t"tipo_evento"\t"observacao"\t"cod_loteamento"\t"nivel_confianca_loteamento"\t"polaridade_evento"\t"tipo_origem_evento"']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_14_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_18_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_21_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_24_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_25_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_26_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_27_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_28_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_29_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_31_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_02_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_05_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_07_tribuna_liberal.csv -> ['data_publicacao', 'titulo_evento', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo_evento', 'localidade', 'tipo_evento', 'nivel_criticidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_08_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_09_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_10_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_11_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']

In [24]:
dfs = []

for f in arquivos:
    df = pd.read_csv(f)
    df["arquivo_origem"] = f
    dfs.append(df)

df_total = pd.concat(dfs, ignore_index=True)

print(df_total)

               fonte        data  \
0    Tribuna Liberal  2026-03-01
1    Tribuna Liberal  2026-03-01
2    Tribuna Liberal  2026-03-01
3    Tribuna Liberal  2026-03-01
4    Tribuna Liberal  2026-03-01
..               ...         ...
109  Tribuna Liberal  2026-04-10
110  Tribuna Liberal  2026-03-29
111  Tribuna Liberal  2026-03-29
112  Tribuna Liberal  2026-03-29
113  Tribuna Liberal  2026-03-29

                                                  item pagina  \
0       Familias atingidas pela chuva - Jardim Ricardo      9
1    Familias atingidas pela chuva - Jardim Sumarez...      9
2      Familias atingidas pela chuva - Jardim Adelaide      9
3    Familias atingidas pela chuva - Jardim Santa C...      9
4    Programa Acerte abre cadastro - Costura Indust...      6
..                                                 ...    ...
109  Hospital Metropolitano Campinas - licitacao ab...     10
110       Conserto erosao frente EMEIEF Jd. Amanda III      9
111   Paulinia - Lei 4685/2026 matricula maes atipicas      9
112    STF - visao monocular como deficiencia ADI 6850      9
113  Ana Perugini - R$ 1.57 mi Centro Inteligencia ...      7

              dimensao_ivs codigo_variavel tipo_relacao_variavel  \
0    infraestrutura_urbana           IU_01                direta
1    infraestrutura_urbana           IU_01                direta
2    infraestrutura_urbana           IU_01                direta
3    infraestrutura_urbana           IU_01                direta
4           renda_trabalho           RT_02              indireta
..                     ...             ...                   ...
109         capital_humano           CH_01            contextual
110  infraestrutura_urbana           IU_01                direta
111         capital_humano           CH_05                direta
112         capital_humano           CH_05                direta
113         capital_humano           RT_04                direta

    nivel_criticidade                                             resumo  \
0                alta  Chuva de 82mm na madrugada de 26/02 inunda cas...
1                alta  Chuva de 82mm na madrugada de 26/02 inunda cas...
2                alta  Chuva de 82mm na madrugada de 26/02 inunda cas...
3                alta  Chuva de 82mm na madrugada de 26/02 inunda cas...
4               media  Prefeitura abre cadastro para Programa Acerte ...
..                ...                                                ...
109               NaN  Estado abre licitacao para Hospital Metropolit...
110               NaN  Reparo de afundamento de solo na Rua Duque de ...
111               NaN  Paulinia sanciona lei de prioridade de matricu...
112               NaN  STF confirma visao monocular como deficiencia ...
113               NaN  Emenda para Centro de Inteligencia Social: con...

          origem  ...  tipo_origem_evento  \
0    Hortolandia  ...      infraestrutura
1    Hortolandia  ...      infraestrutura
2    Hortolandia  ...      infraestrutura
3    Hortolandia  ...      infraestrutura
4    Hortolandia  ...  assistencia_social
..           ...  ...                 ...
109     Regional  ...      infraestrutura
110  Hortolandia  ...           seguranca
111     Regional  ...       institucional
112     Regional  ...       institucional
113  Hortolandia  ...       institucional

                                        arquivo_origem  \
0    C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
1    C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
2    C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
3    C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
4    C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
..                                                 ...
109  C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
110  C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
111  C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
112  C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
113  C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...

    fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
109                                                NaN
110                                                NaN
111                                                NaN
112                                                NaN
113                                                NaN

    data_publicacao\ttitulo_evento\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tresumo_evento\tlocalidade\ttipo_evento\tnivel_criticidade\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
109                                                NaN
110                                                NaN
111                                                NaN
112                                                NaN
113                                                NaN

    fonte\t"data"\t"item"\t"pagina"\t"dimensao_ivs"\t"codigo_variavel"\t"tipo_relacao_variavel"\t"nivel_criticidade"\t"resumo"\t"origem"\t"municipio_impactado"\t"tipo_abrangencia"\t"tipo_evento"\t"observacao"\t"cod_loteamento"\t"nivel_confianca_loteamento"\t"polaridade_evento"\t"tipo_origem_evento"  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
109                                                NaN
110                                                NaN
111                                                NaN
112                                                NaN
113                                                NaN

    gravidade data_publicacao titulo_evento resumo_evento localidade
0         NaN             NaN           NaN           NaN        NaN
1         NaN             NaN           NaN           NaN        NaN
2         NaN             NaN           NaN           NaN        NaN
3         NaN             NaN           NaN           NaN        NaN
4         NaN             NaN           NaN           NaN        NaN
..        ...             ...           ...           ...        ...
109     media             NaN           NaN           NaN        NaN
110     media             NaN           NaN           NaN        NaN
111     media             NaN           NaN           NaN        NaN
112     media             NaN           NaN           NaN        NaN
113     media             NaN           NaN           NaN        NaN

[114 rows x 27 columns]

In [10]:
df_total['dimensao_ivs'].value_counts()

dimensao_ivs
capital_humano           34
infraestrutura_urbana    24
renda_trabalho           13
multidimensional          7
governanca                6
SMIDS_EXT                 2
Name: count, dtype: int64

In [11]:
df_total['polaridade_evento'].value_counts()

polaridade_evento
positivo    50
negativo    37
neutro       1
Name: count, dtype: int64

In [12]:
df_total['nivel_criticidade'].value_counts()

nivel_criticidade
media     10
alta       8
baixa      6
alerta     4
Name: count, dtype: int64

In [13]:
df_total['tipo_evento'].value_counts()

tipo_evento
politica_publica        31
problema                19
infraestrutura          13
violencia                8
indicador                4
caso_individual          3
acao_institucional       3
institucional            2
vulnerabilidade          1
economia                 1
pressao_orcamentaria     1
seguranca                1
governanca               1
Name: count, dtype: int64

In [14]:
mapa_loteamentos = {
    "351": "Jardim Amanda",
    "93": "Jardim Ricardo",
    "86": "Jardim Sumarezinho",
    "333": "Jardim Adelaide"
}

In [15]:
df_total["nome_loteamento"] = df_total["cod_loteamento"].map(mapa_loteamentos)

In [16]:
df_total["nome_loteamento"].value_counts()

nome_loteamento
Jardim Amanda         7
Jardim Ricardo        1
Jardim Sumarezinho    1
Jardim Adelaide       1
Name: count, dtype: int64

In [17]:
df_total[df_total['cod_loteamento'] != 'nao_aplicavel']['cod_loteamento'].value_counts()

cod_loteamento
351                       7
66                        3
317                       2
sem_codigo_monte_sinai    2
63                        2
57                        2
93                        1
457                       1
342                       1
306                       1
341                       1
370                       1
nao_identificado          1
318                       1
86                        1
398                       1
457                       1
319                       1
Chacaras 2000             1
307                       1
383                       1
333                       1
331                       1
Name: count, dtype: int64

In [18]:
df_filtrado = df_total[
    ~df_total["dimensao_ivs"].isin(["governanca", "SMIDS_EXT"])
]

In [19]:
print(len(df_total))

114

In [20]:
df_total['dimensao_ivs'].isna().sum()
df_total['polaridade_evento'].isna().sum()
df_total['nivel_criticidade'].isna().sum()
df_total['tipo_evento'].isna().sum()

26

In [21]:
df_total[df_total['dimensao_ivs'].isna()][['titulo_evento','tipo_evento','tipo_origem_evento']]

,titulo_evento,tipo_evento,tipo_origem_evento
17,NaN,NaN,NaN
18,NaN,NaN,NaN
19,NaN,NaN,NaN
20,NaN,NaN,NaN
21,NaN,NaN,NaN
22,NaN,NaN,NaN
23,NaN,NaN,NaN
24,NaN,NaN,NaN
25,NaN,NaN,NaN
26,NaN,NaN,NaN
27,NaN,NaN,NaN
28,NaN,NaN,NaN
29,NaN,NaN,NaN
30,NaN,NaN,NaN
31,NaN,NaN,NaN
32,NaN,NaN,NaN
33,NaN,NaN,NaN
34,NaN,NaN,NaN
35,NaN,NaN,NaN
36,NaN,NaN,NaN
37,NaN,NaN,NaN
38,NaN,NaN,NaN
39,NaN,NaN,NaN
40,NaN,NaN,NaN
41,NaN,NaN,NaN
42,NaN,NaN,NaN
89,Ciclista de 40 anos atropelado e morto por cam...,caso_individual,seguranca
92,Sarau Parada Poetica - participacao de Criolo ...,acao_institucional,cultura

In [22]:
df_total.iloc[15:45]

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,...,arquivo_origem,fonte\tdata\titem\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tnivel_criticidade\tresumo\torigem\tmunicipio_impactado\ttipo_abrangencia\ttipo_evento\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento,data_publicacao\ttitulo_evento\tpagina\tdimensao_ivs\tcodigo_variavel\ttipo_relacao_variavel\tresumo_evento\tlocalidade\ttipo_evento\tnivel_criticidade\tobservacao\tcod_loteamento\tnivel_confianca_loteamento\tpolaridade_evento\ttipo_origem_evento,"fonte\t""data""\t""item""\t""pagina""\t""dimensao_ivs""\t""codigo_variavel""\t""tipo_relacao_variavel""\t""nivel_criticidade""\t""resumo""\t""origem""\t""municipio_impactado""\t""tipo_abrangencia""\t""tipo_evento""\t""observacao""\t""cod_loteamento""\t""nivel_confianca_loteamento""\t""polaridade_evento""\t""tipo_origem_evento""",gravidade,data_publicacao,titulo_evento,resumo_evento,localidade,nome_loteamento
15,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,4,renda_trabalho,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Tribuna Liberal,2026-03-04,UBS Animal - busca de emenda federal,8,infraestrutura_urbana,NaN,contextual,baixa,Prefeito recebe representantes do deputado Bru...,Hortolandia,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tMCMV - 400 unidad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tBriga com dois ba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tPainel violencia ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tInterdicao de pon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tVisita do prefeit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-05\tETE Hortolandia -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-06\tAuxilio-refeicao ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-06\tMCMV - 576 docume...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-06\tFatec Hortolandia...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-06\tPrisao preventiva...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-07\tFestival Vozes da...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-07\tEMS anuncia compr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-07\tViaduto Vila Real...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Tribuna Liberal\t2026-03-07\tCloset Solidario ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,08/03/2026\tSuelen Alves Limeira - de desempre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,08/03/2026\tJustica condena ex-servidor por at...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,08/03/2026\tCampanha Emplaca Hortolandia encer...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,08/03/2026\tCaderno Mulher - Tribuna Liberal p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""fatec_hortolan...",NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""monte_sinai_sa...",NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""juri_condena_a...",NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""violencia_dome...",NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""mulher_presa_5...",NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-10""\t""homem_preso_fu...",NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-12""\t""forca_tarefa_r...",NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,"tribuna_liberal\t""2026-03-12""\t""homem_44_anos_...",NaN,NaN,NaN,NaN,NaN,NaN
43,Tribuna Liberal,2026-03-14,Medidas protetivas,s/n,capital_humano,NaN,indireta,alta,94 medidas protetivas em jan-fev/2026 maior vo...,Hortolandia,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Tribuna Liberal,2026-03-14,Homicídio em madeireira,s/n,capital_humano,NaN,contextual,alta,Homem é assassinado a tiros durante ataque a m...,Hortolandia,...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN