In [1]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,observacao,nota_analista
0,Tribuna Liberal,2026-03-04,ETE Hortolandia - 18 multas Cetesb em dez meses,4,infraestrutura_urbana,IU_01,direta,alerta,ETE de Hortolandia acumulou 18 multas da Cetes...,Hortolandia,Hortolandia,local,indicador,nao_aplicavel,nao_aplicavel,negativo,saneamento,interface_iu,indicador direto de falha em saneamento; impac...
1,Tribuna Liberal,2026-03-04,Pai sequestra filha de 2 anos - Jardim Amanda,9,capital_humano,NaN,contextual,alerta,Pai sequestra filha de 2 anos no Jardim Amanda...,Hortolandia,Hortolandia,local,problema,351,alto,negativo,seguranca,sinal_smids_ext,sinal_SMIDS_EXT
2,Tribuna Liberal,2026-03-04,Regularizacao fundiaria e habitacao - reuniao ...,8,infraestrutura_urbana,IU_01,indireta,media,Prefeito reune-se com secretario estadual de H...,Hortolandia,Hortolandia,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,habitacao,multiplos_loteamentos,multiplos_loteamentos
3,Tribuna Liberal,2026-03-04,Obra de drenagem - Jardim Novo Angulo,8,infraestrutura_urbana,IU_01,indireta,media,Maquinas iniciam obras de reparo de erosao na ...,Hortolandia,Hortolandia,local,politica_publica,307,medio,positivo,infraestrutura,NaN,NaN
4,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,4,SMIDS_EXT,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,Hortolandia,local,problema,nao_aplicavel,nao_aplicavel,negativo,economia,sinal_smids_ext,sinal_SMIDS_EXT

In [2]:
import pandas as pd

arquivos = [
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv"
]

dfs = [pd.read_csv(f) for f in arquivos]

df_total = pd.concat(dfs, ignore_index=True)

df_total.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,observacao,nota_analista
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,93,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,86,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,333,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,317,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,6,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,assistencia_social,acao_institucional_smids,Sem limite de vagas - funciona como Banco de T...

O r significa: “não interprete as barras como código” e simples e tab funicona "C:/Users/ailto/Atlas-Social-de-Hortolandia/00_governanca/series_jornalisticas/2026_03_01_tribuna_liberal.csv"                                                                          
📍 O que é ignore_index=True

Quando você usa:

df_total = pd.concat(dfs, ignore_index=True)

você está dizendo ao pandas:

“Ignore os índices originais de cada DataFrame e crie um novo índice contínuo.”

🧠 Vamos entender com calma
🔹 Cada CSV tem seu próprio índice

Quando você lê um arquivo:

df = pd.read_csv(...)

ele vem assim:

0
1
2
3

Agora imagine que você tem 5 arquivos.

Cada um deles começa do zero:

Arquivo 1 → 0,1,2,3
Arquivo 2 → 0,1,2
Arquivo 3 → 0,1,2,3,4
🔴 Se você NÃO usar ignore_index
df_total = pd.concat(dfs)

Resultado:

0
1
2
3
0
1
2
0
1
2
3
4

👉 Índices repetidos
👉 Bagunça lógica
👉 Pode dar erro em análises futuras

🟢 Se você usar ignore_index=True
df_total = pd.concat(dfs, ignore_index=True)

Resultado:

0
1
2
3
4
5
6
7
8
9
10
...

👉 índice único
👉 contínuo
👉 limpo para análise

📊 Interpretação conceitual (importante para o seu projeto)

No seu caso:

Você está criando um dataset consolidado de notícias.

Então faz total sentido dizer:

“Cada linha agora é um evento único no tempo — não importa de qual arquivo veio.”

Logo:

✔️ índice novo = identidade do dataset consolidado
❌ índice antigo = identidade do arquivo original (não interessa mais)

⚠️ Quando NÃO usar ignore_index

Você NÃO usaria se:

o índice tem significado (ex: ID único)
você quer rastrear origem linha a linha pelo índice

Mas no seu caso:

👉 você já tem:

data
fonte
item

Então o índice não tem valor analítico.

🧭 Tradução prática
Situação	Usar ignore_index
Juntar vários CSVs iguais	✅ Sim
Criar base única de análise	✅ Sim
Índice tem significado (ID)	❌ Não
📌 Em uma frase

ignore_index=True transforma vários arquivos separados em uma única tabela contínua e coerente para análise.

In [3]:
import pandas as pd
import glob

pasta = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

arquivos = glob.glob(pasta + r"\2026_*_*_tribuna_liberal.csv")

arquivos

['C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_04_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_06_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_07_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_08_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_10_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_12_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_14_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_18_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_21_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_24_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_25_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_26_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_27_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_28_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_29_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_31_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_02_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_07_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_08_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_09_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_10_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_11_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_12_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_16_tribuna_liberal.csv']

In [4]:
for f in arquivos:
    try:
        df = pd.read_csv(f)
        print(f, "->", list(df.columns))
    except Exception as e:
        print(f, "-> ERRO:", e)

C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_07_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_08_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_10_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_12_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_14_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_18_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_21_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_24_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_25_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_26_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_27_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_28_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_29_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_31_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_02_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_05_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_07_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_08_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_09_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_10_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_11_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_12_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_16_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento', 'observacao', 'nota_analista']

dfs = []

for f in arquivos:
    df = pd.read_csv(f)
    df["arquivo_origem"] = f
    dfs.append(df)

df_total = pd.concat(dfs, ignore_index=True)

print(df_total)

In [5]:
import csv
import pandas as pd
import os

PASTA = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

arquivos = [
    os.path.join(PASTA, f)
    for f in sorted(os.listdir(PASTA))
    if f.endswith(".csv") and f != "corpus_resumo_periodos_v07.csv"
]

dfs = []
for f in arquivos:
    df = pd.read_csv(f, dtype=str, quoting=csv.QUOTE_ALL)
    df["arquivo_origem"] = f
    dfs.append(df)

df_total = pd.concat(dfs, ignore_index=True)
print(df_total.shape)
df_total.head(10)

(98, 20)

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,observacao,nota_analista,arquivo_origem
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,09,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,93,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,09,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,86,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,09,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,333,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,09,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,317,alto,negativo,infraestrutura,acao_institucional_smids,Defesa Civil fez triagem e acionou secretarias...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,06,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,assistencia_social,acao_institucional_smids,Sem limite de vagas - funciona como Banco de T...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
5,Tribuna Liberal,2026-03-01,Relatorio jogos online - risco a criancas e ad...,05,capital_humano,CH_03,contextual,media,Relatorio do NOAD/Policia Civil entregue ao MP...,Regional,Hortolandia,regional,problema,nao_aplicavel,nao_aplicavel,negativo,seguranca,interface_ch,Nucleo monitora 1200 alvos 24h/dia; apresentac...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
6,Tribuna Liberal,2026-03-03,Viaduto Vila Real - rotatoria comeca proxima s...,07,infraestrutura_urbana,IU_03,indireta,media,Prefeitura recebe documentacao do projeto da r...,Hortolandia,Hortolandia,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,mobilidade,interface_iu,Conecta Av. Santana Jd. Amanda ao Centro e Nov...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
7,Tribuna Liberal,2026-03-03,Mpox - caso confirmado em Hortolandia,05,capital_humano,NaN,indireta,media,Hortolandia figura entre municipios com casos ...,Hortolandia,Hortolandia,regional,indicador,nao_aplicavel,nao_aplicavel,negativo,saude,impacto_regional_hortolandia,Hortolandia Paulinia e Americana integram list...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
8,Tribuna Liberal,2026-03-03,Mes da Mulher - evento para 200 servidoras no ...,07,capital_humano,NaN,indireta,baixa,Prefeitura reune 200 servidoras na abertura do...,Hortolandia,Hortolandia,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,assistencia_social,acao_institucional_smids,Organizado pelo Departamento das Mulheres; dir...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...
9,Tribuna Liberal,2026-03-03,Carro invade Escola Estadual Maria Rita Araujo...,10,capital_humano,CH_03,contextual,alta,Carro invade Escola Estadual no Parque Terras ...,Hortolandia,Hortolandia,local,problema,383,medio,negativo,transito,sinal_smids_ext,Veiculo registrado em nome de terceiro; ocupan...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...

In [6]:
df_total['dimensao_ivs'].value_counts()

dimensao_ivs
capital_humano           37
infraestrutura_urbana    27
renda_trabalho           13
multidimensional          7
governanca                7
SMIDS_EXT                 5
Name: count, dtype: int64

In [7]:
df_total['polaridade_evento'].value_counts()

polaridade_evento
positivo    57
negativo    40
neutro       1
Name: count, dtype: int64

In [8]:
df_total['nivel_criticidade'].value_counts()

nivel_criticidade
media            52
alta             27
baixa            13
alerta            5
nao_aplicavel     1
Name: count, dtype: int64

In [9]:
df_total['tipo_evento'].value_counts()

tipo_evento
politica_publica        37
problema                21
infraestrutura          13
violencia                8
indicador                6
caso_individual          3
acao_institucional       3
institucional            2
vulnerabilidade          1
economia                 1
pressao_orcamentaria     1
seguranca                1
governanca               1
Name: count, dtype: int64

In [10]:
mapa_loteamentos = {
    "351": "Jardim Amanda",
    "93": "Jardim Ricardo",
    "86": "Jardim Sumarezinho",
    "333": "Jardim Adelaide"
}

In [11]:
df_total["nome_loteamento"] = df_total["cod_loteamento"].map(mapa_loteamentos)

In [12]:
df_total["nome_loteamento"].value_counts()

nome_loteamento
Jardim Amanda         7
Jardim Ricardo        1
Jardim Sumarezinho    1
Jardim Adelaide       1
Name: count, dtype: int64

In [13]:
df_total[df_total['cod_loteamento'] != 'nao_aplicavel']['cod_loteamento'].value_counts()

cod_loteamento
351                       7
66                        4
63                        2
317                       2
457                       2
nao_identificado          2
sem_codigo_monte_sinai    2
57                        2
93                        1
342                       1
306                       1
341                       1
370                       1
318                       1
86                        1
398                       1
319                       1
Chacaras 2000             1
307                       1
383                       1
333                       1
331                       1
Name: count, dtype: int64

In [14]:
df_filtrado = df_total[
    ~df_total["dimensao_ivs"].isin(["governanca", "SMIDS_EXT"])
]

In [15]:
print(len(df_total))

98

In [16]:
df_total['dimensao_ivs'].isna().sum()
df_total['polaridade_evento'].isna().sum()
df_total['nivel_criticidade'].isna().sum()
df_total['tipo_evento'].isna().sum()

0

In [17]:
import pandas as pd
import os
import csv

PASTA = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

arquivos_limpos = 0
linhas_removidas_total = 0

for arquivo in sorted(os.listdir(PASTA)):
    if not arquivo.endswith(".csv"):
        continue
    if arquivo == "corpus_resumo_periodos_v07.csv":
        continue

    caminho = os.path.join(PASTA, arquivo)
    df = pd.read_csv(caminho, dtype=str, quoting=csv.QUOTE_ALL)

    linhas_antes = len(df)
    df = df.dropna(how="all")
    linhas_depois = len(df)
    removidas = linhas_antes - linhas_depois

    if removidas > 0:
        df.to_csv(caminho, index=False, quoting=csv.QUOTE_ALL, encoding="utf-8")
        print(f"✅ {arquivo} — {removidas} linha(s) removida(s)")
        linhas_removidas_total += removidas
    else:
        print(f"   {arquivo} — sem linhas vazias")

    arquivos_limpos += 1

print()
print(f"Arquivos verificados   : {arquivos_limpos}")
print(f"Linhas vazias removidas: {linhas_removidas_total}")

   2026_03_01_tribuna_liberal.csv — sem linhas vazias
   2026_03_03_tribuna_liberal.csv — sem linhas vazias
   2026_03_04_tribuna_liberal.csv — sem linhas vazias
   2026_03_05_tribuna_liberal.csv — sem linhas vazias
   2026_03_06_tribuna_liberal.csv — sem linhas vazias
   2026_03_07_tribuna_liberal.csv — sem linhas vazias
   2026_03_08_tribuna_liberal.csv — sem linhas vazias
   2026_03_10_tribuna_liberal.csv — sem linhas vazias
   2026_03_12_tribuna_liberal.csv — sem linhas vazias
   2026_03_14_tribuna_liberal.csv — sem linhas vazias
   2026_03_18_tribuna_liberal.csv — sem linhas vazias
   2026_03_21_tribuna_liberal.csv — sem linhas vazias
   2026_03_24_tribuna_liberal.csv — sem linhas vazias
   2026_03_25_tribuna_liberal.csv — sem linhas vazias
   2026_03_26_tribuna_liberal.csv — sem linhas vazias
   2026_03_27_tribuna_liberal.csv — sem linhas vazias
   2026_03_28_tribuna_liberal.csv — sem linhas vazias
   2026_03_29_tribuna_liberal.csv — sem linhas vazias
   2026_03_31_tribuna_liberal.csv — sem linhas vazias
   2026_04_01_tribuna_liberal.csv — sem linhas vazias
   2026_04_02_tribuna_liberal.csv — sem linhas vazias
   2026_04_03_tribuna_liberal.csv — sem linhas vazias
   2026_04_05_tribuna_liberal.csv — sem linhas vazias
   2026_04_07_tribuna_liberal.csv — sem linhas vazias
   2026_04_08_tribuna_liberal.csv — sem linhas vazias
   2026_04_09_tribuna_liberal.csv — sem linhas vazias
   2026_04_10_tribuna_liberal.csv — sem linhas vazias
   2026_04_11_tribuna_liberal.csv — sem linhas vazias
   2026_04_12_tribuna_liberal.csv — sem linhas vazias
   2026_04_16_tribuna_liberal.csv — sem linhas vazias

Arquivos verificados   : 30
Linhas vazias removidas: 0

In [19]:
df_total.iloc[15:45]

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,...,tipo_abrangencia,tipo_evento,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,observacao,nota_analista,arquivo_origem,nome_loteamento
15,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,04,SMIDS_EXT,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,economia,sinal_smids_ext,sinal_SMIDS_EXT,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
16,Tribuna Liberal,2026-03-04,UBS Animal - busca de emenda federal,08,infraestrutura_urbana,NaN,latente,baixa,Prefeito recebe representantes do deputado Bru...,Hortolandia,...,local,politica_publica,Chacaras 2000,baixo,positivo,saude,impacto_latente,impacto_latente,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
17,Tribuna Liberal,2026-03-14,Medidas protetivas,s/n,capital_humano,NaN,indireta,alta,94 medidas protetivas em jan-fev/2026 maior vo...,Hortolandia,...,local,indicador,nao_aplicavel,nao_aplicavel,negativo,seguranca,interface_ch,Indicador de violência doméstica e fragilidade...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
18,Tribuna Liberal,2026-03-14,Homicídio em madeireira,s/n,capital_humano,NaN,contextual,alta,Homem é assassinado a tiros durante ataque a m...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,seguranca,sinal_smids_ext,Evento de violência urbana associado à pressão...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
19,Tribuna Liberal,2026-03-14,Acidente fatal com motocicleta,s/n,capital_humano,NaN,contextual,alta,Adolescente morre após motocicleta bater contr...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,transito,interface_ch,Evento relacionado a risco juvenil e possível ...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
20,Tribuna Liberal,2026-03-18,Forum de Empregabilidade,s/n,renda_trabalho,NaN,indireta,media,Forum Dimas + Maria dos Anjos vinculado ao pro...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,interface_rt,Ação institucional de promoção de empregabilid...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
21,Tribuna Liberal,2026-03-18,Embalixo 5x2,s/n,renda_trabalho,NaN,indireta,media,110 contratacoes formais; dado futuro para cru...,Hortolandia,...,local,indicador,nao_aplicavel,nao_aplicavel,positivo,institucional,interface_rt,Evidência empírica de inserção produtiva forma...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
22,Tribuna Liberal,2026-03-18,Ministra das Mulheres Jardim Amanda,s/n,capital_humano,NaN,contextual,media,Visita ao nucleo Amanda; contexto de vulnerabi...,Hortolandia,...,local,politica_publica,351,alto,positivo,institucional,dado_auditavel,Território com alta presença no CadUnico (1020...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Jardim Amanda
23,Tribuna Liberal,2026-03-21,Exposicao Mulheres que Inspiram,s/n,capital_humano,CH_04,direta,media,Acao SMIDS/DPP PcD no Palacio dos Migrantes - ...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,fora_escopo_smids,Acao pontual nao entra no catalogo de programas,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
24,Tribuna Liberal,2026-03-21,Residencial Senior Terca da Serra,s/n,renda_trabalho,RT_04,contextual,media,Segunda unidade no Parque Ortolandia - 30 leit...,Hortolandia,...,local,infraestrutura,nao_aplicavel,nao_aplicavel,positivo,infraestrutura,interface_rt,Impacto futuro em RT_04 Economia Prateada,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
25,Tribuna Liberal,2026-03-21,17a Caravana Federativa equipamentos saude,s/n,capital_humano,CH_01,direta,media,Saude recebeu equipamentos de fisioterapia rea...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,interface_ch,Amplia capacidade de resposta Capital Humano,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
26,Tribuna Liberal,2026-03-21,"Reajuste funcionalismo 2,51%",s/n,renda_trabalho,RT_01,direta,media,Lei 4606/2026 - 5200 servidores - IPCA 10 meses,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,interface_rt,Contexto de custo de vida e pressao sobre renda,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
27,Tribuna Liberal,2026-03-24,Mercado imobiliario +10%,s/n,infraestrutura_urbana,IU_01,direta,media,Crescimento imobiliario Sumare e Hortolandia\t...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,seguranca,interface_iu,Indicador de expansao territorial impacto em I...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
28,Tribuna Liberal,2026-03-24,Parque Terras de Santa Maria,s/n,infraestrutura_urbana,IU_01,direta,media,Obras iniciadas\t evento positivo de infraestr...,Hortolandia,...,local,infraestrutura,nao_aplicavel,nao_aplicavel,positivo,infraestrutura,tarefa_pendente,Verificar nome oficial do programa com Sec. Me...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
29,Tribuna Liberal,2026-03-24,TCE-SP auditorias operacionais 2026,s/n,infraestrutura_urbana,SMIDS_EXT,contextual,media,TCE-SP amplia auditorias em municipios\t argum...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,dado_auditavel,Rastreabilidade e evidencia tecnica como respo...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
30,Tribuna Liberal,2026-03-25,UBS Terras de Santa Maria,s/n,capital_humano,CH_01,direta,media,Obras da UBS iniciadas\t expansao da rede de s...,Hortolandia,...,local,infraestrutura,nao_aplicavel,nao_aplicavel,positivo,infraestrutura,fora_escopo_smids,Equipamento de saude fora do escopo SMIDS,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
31,Tribuna Liberal,2026-03-25,CAPS Vida Jardim America,s/n,capital_humano,CH_08,direta,media,CAPS autorizado\t saude mental\t interface fut...,Hortolandia,...,local,infraestrutura,nao_aplicavel,nao_aplicavel,positivo,infraestrutura,fora_escopo_smids,Equipamento de saude fora do escopo SMIDS,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
32,Tribuna Liberal,2026-03-25,PROUNI Hortolandia,s/n,capital_humano,CH_07,direta,media,Proposta legislativa de acesso ao PROUNI\t imp...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,tarefa_pendente,Indicacao legislativa - aguarda aprovacao moni...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
33,Tribuna Liberal,2026-03-25,Gasolina media R$ 6.41,s/n,renda_trabalho,RT_01,direta,alta,Procon fiscaliza postos\t preco medio regional...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,economico,interface_rt,Pressao de custo de vida sobre renda familiar ...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
34,Tribuna Liberal,2026-03-26,Programa Cuidar,9,capital_humano,CH_04,direta,media,Entrega de kits de maternidade (6025 kits desd...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,acao_institucional_smids,Acao institucional SMIDS,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
35,Tribuna Liberal,2026-03-26,Abastecimento BRK,9,infraestrutura_urbana,IU_01,direta,media,Oscilacao de abastecimento em 14 bairros em 31/03,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,infraestrutura,multiplos_loteamentos,Cruzar com loteamentos afetados,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
36,Tribuna Liberal,2026-03-26,Idoso encontrado morto,8,capital_humano,CH_05,indireta,alta,Idoso sozinho em situacao de vulnerabilidade (...,Hortolandia,...,local,caso_individual,319,alto,negativo,assistencial,sinal_smids_ext,Vulnerabilidade individual com possivel isolam...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
37,Tribuna Liberal,2026-03-27,Manifesto servidores vale-alimentação,1,renda_trabalho,RT_01,direta,media,Servidores municipais pedem vale-refeição; PL ...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,contexto_sociopolitico,Contexto político relevante para período de ap...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
38,Tribuna Liberal,2026-03-27,Protocolo Coordenação Pedagógica,8,capital_humano,CH_07,direta,media,Lançamento de protocolo formativo para coorden...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,interface_ch,Ação da Educação; interface com CH_03 e CH_07;...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
39,Tribuna Liberal,2026-03-27,Zeladoria Parque Lago da Fé,8,SMIDS_EXT,SMIDS_EXT,contextual,media,Mutirão de manutenção no Parque Lago da Fé (Pa...,Hortolandia,...,local,infraestrutura,nao_aplicavel,nao_aplicavel,positivo,infraestrutura,caso_ilustrativo,Parque Gabriel em área de vulnerabilidade; rel...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
40,Tribuna Liberal,2026-03-27,Furto de carga Jardim Amanda,9,SMIDS_EXT,SMIDS_EXT,indireta,media,Quatro presos por furto de óleo na Av. Princes...,Hortolandia,...,local,problema,351,alto,negativo,seguranca,sinal_smids_ext,Ocorrência de segurança no Jd. Amanda; bairro ...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Jardim Amanda
41,Tribuna Liberal,2026-03-28,Parque Jd. Amanda - espaco patinacao,4,multidimensional,SMIDS_EXT,contextual,media,Implantacao de area de patinacao no Parque Soc...,Hortolandia,...,local,infraestrutura,351,alto,positivo,infraestrutura,caso_ilustrativo,Equipamento publico em loteamento de interesse,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,Jardim Amanda
42,Tribuna Liberal,2026-03-28,ISLU 2025 - Hortolandia 1301a posicao,6,infraestrutura_urbana,IU_02,direta,media,Hortolandia posicao 1301 indice 0.538 conceito...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,seguranca,dado_auditavel,Dado auditavel corrobora IU_02,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
43,Tribuna Liberal,2026-03-28,Tentativa de estupro em praca publica,9,multidimensional,CH_05,indireta,alta,Tentativa de estupro em praca proxima ao Hospi...,Hortolandia,...,local,problema,nao_aplicavel,nao_aplicavel,negativo,seguranca,interface_ch,Violencia de genero em espaco publico; interfa...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
44,Tribuna Liberal,2026-03-28,Ana Perugini - R$ 400 mil CRAS Jardim Brasil,7,multidimensional,governanca,contextual,media,Emenda de R$ 400 mil para ampliacao do CRAS Ja...,Hortolandia,...,local,politica_publica,nao_aplicavel,nao_aplicavel,positivo,institucional,acao_institucional_smids,Ampliacao de CRAS relevante para modelagem de ...,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN

In [20]:
print("Total de linhas no df_total:", len(df_total))

Total de linhas no df_total: 98

In [21]:
colunas_chave = ['fonte', 'data', 'item', 'pagina']

df_total[colunas_chave].isna().sum()

fonte     0
data      0
item      0
pagina    0
dtype: int64

In [ ]:
df_vazias = df_total[df_total.isna().all(axis=1)]

print("Linhas totalmente vazias:", len(df_vazias))
df_vazias.head(10)

In [ ]:
df_suspeitas = df_total[
    df_total['item'].isna() |
    df_total['data'].isna() |
    df_total['fonte'].isna()
]

print("Linhas suspeitas:", len(df_suspeitas))
df_suspeitas.head(20)

In [ ]:
df_validas = df_total[
    df_total['item'].notna() &
    df_total['data'].notna() &
    df_total['fonte'].notna()
]

print("Linhas potencialmente válidas:", len(df_validas))
df_validas.head(10)

In [ ]:
df_suspeitas.iloc[0:20]

In [ ]:
df_suspeitas[['fonte', 'data', 'item', 'pagina', 'resumo', 'observacao']].head(20)

In [ ]:
print("Resumo do diagnóstico:")
print("Total:", len(df_total))
print("Totalmente vazias:", len(df_vazias))
print("Suspeitas:", len(df_suspeitas))
print("Potencialmente válidas:", len(df_validas))

In [ ]:
import pandas as pd
import os
import csv

pasta = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

resultados = []

for arquivo in sorted(os.listdir(pasta)):
    if arquivo.endswith(".csv"):
        caminho = os.path.join(pasta, arquivo)
        df = pd.read_csv(caminho, dtype=str, quoting=csv.QUOTE_ALL)
        
        if "observacao" in df.columns:
            for val in df["observacao"].dropna().unique():
                resultados.append({
                    "arquivo": arquivo,
                    "observacao": val.strip(),
                    "ocorrencias": int((df["observacao"].str.strip() == val.strip()).sum())
                })
        else:
            resultados.append({
                "arquivo": arquivo,
                "observacao": "⚠️ COLUNA AUSENTE",
                "ocorrencias": 0
            })

resumo = pd.DataFrame(resultados)
print(f"Total de arquivos: {len(os.listdir(pasta))}")
print(f"Total de valores distintos: {resumo['observacao'].nunique()}")
print()
print(resumo.to_string(index=False))

In [ ]:
import csv
import pandas as pd
import os

PASTA = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

for f in sorted(os.listdir(PASTA)):
    if not f.endswith(".csv") or f == "corpus_resumo_periodos_v07.csv":
        continue
    caminho = os.path.join(PASTA, f)
    df = pd.read_csv(caminho, dtype=str)
    print(f"{f}: {list(df.columns)}")

In [26]:
import pandas as pd
import os
import csv

PASTA = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

dfs = []
for arquivo in sorted(os.listdir(PASTA)):
    if not arquivo.endswith('.csv') or arquivo == 'corpus_resumo_periodos_v07.csv':
        continue
    caminho = os.path.join(PASTA, arquivo)
    df = pd.read_csv(caminho, dtype=str)
    df["arquivo_origem"] = arquivo
    dfs.append(df)

df_total = pd.concat(dfs, ignore_index=True)

# Verificação 1 — linhas suspeitas
suspeitas = df_total[df_total['fonte'].isna() | df_total['data'].isna()]

# Verificação 2 — colunas canônicas presentes
COLUNAS_CANONICAS = [
    'fonte', 'data', 'item', 'pagina',
    'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel',
    'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado',
    'tipo_abrangencia', 'tipo_evento', 'cod_loteamento',
    'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento',
    'observacao', 'nota_analista'
]
colunas_faltando = [c for c in COLUNAS_CANONICAS if c not in df_total.columns]

# Verificação 3 — valores de observacao fora do vocabulário
VOCABULARIO = {
    'sinal_smids_ext', 'multiplos_loteamentos', 'impacto_latente',
    'impacto_regional_hortolandia', 'aproximacao_variavel', 'caso_ilustrativo',
    'interface_ch', 'interface_rt', 'interface_iu', 'dado_auditavel',
    'fora_escopo_smids', 'acao_institucional_smids', 'duvida_metodologica',
    'tarefa_pendente', 'contexto_sociopolitico', ''
}
obs_invalidas = df_total[~df_total['observacao'].fillna('').isin(VOCABULARIO)]

# Verificação 4 — gravidade ainda presente
tem_gravidade = 'gravidade' in df_total.columns

print(f"Total de registros      : {len(df_total)}")
print(f"Linhas suspeitas        : {len(suspeitas)}")
print(f"Colunas faltando        : {colunas_faltando if colunas_faltando else 'nenhuma'}")
print(f"Observacoes invalidas   : {len(obs_invalidas)}")
print(f"Coluna gravidade ainda presente : {tem_gravidade}")
print()

if len(suspeitas) == 0 and not colunas_faltando and len(obs_invalidas) == 0 and not tem_gravidade:
    print("✅ Corpus íntegro — pode dormir tranquilo.")
else:
    print("⚠️  Há itens a resolver antes de dormir.")
    if len(obs_invalidas) > 0:
        print()
        print("Observações fora do vocabulário:")
        print(obs_invalidas[['arquivo_origem', 'observacao']].to_string())

Total de registros      : 98
Linhas suspeitas        : 0
Colunas faltando        : nenhuma
Observacoes invalidas   : 0
Coluna gravidade ainda presente : False

✅ Corpus íntegro — pode dormir tranquilo.