In [1]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,93,alto,negativo,infraestrutura
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,86,alto,negativo,infraestrutura
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,333,alto,negativo,infraestrutura
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,317,alto,negativo,infraestrutura
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,6,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,Sem limite de vagas - funciona como Banco de T...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social

In [2]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-03,Viaduto Vila Real - rotatoria comeca proxima s...,7,infraestrutura_urbana,IU_03,indireta,media,Prefeitura recebe documentacao do projeto da r...,Hortolandia,Hortolandia,local,politica_publica,Conecta Av. Santana Jd. Amanda ao Centro e Nov...,nao_aplicavel,nao_aplicavel,positivo,mobilidade
1,Tribuna Liberal,2026-03-03,Mpox - caso confirmado em Hortolandia,5,capital_humano,NaN,indireta,media,Hortolandia figura entre municipios com casos ...,Hortolandia,Hortolandia,regional,indicador,Hortolandia Paulinia e Americana integram list...,nao_aplicavel,nao_aplicavel,negativo,saude
2,Tribuna Liberal,2026-03-03,Mes da Mulher - evento para 200 servidoras no ...,7,capital_humano,NaN,indireta,baixa,Prefeitura reune 200 servidoras na abertura do...,Hortolandia,Hortolandia,local,politica_publica,Organizado pelo Departamento das Mulheres; dir...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social
3,Tribuna Liberal,2026-03-03,Carro invade Escola Estadual Maria Rita Araujo...,10,capital_humano,CH_03,contextual,alta,Carro invade Escola Estadual no Parque Terras ...,Hortolandia,Hortolandia,local,problema,Veiculo registrado em nome de terceiro; ocupan...,383,medio,negativo,transito
4,Tribuna Liberal,2026-03-03,ETE Hortolandia - charge sobre bloqueadores de ar,1,infraestrutura_urbana,NaN,contextual,media,Charge de capa faz referencia a odores da ETE ...,Hortolandia,Hortolandia,local,problema,Charge sugere que Monte Mor autorizou bloquead...,nao_aplicavel,nao_aplicavel,negativo,saneamento

In [3]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-04,ETE Hortolandia - 18 multas Cetesb em dez meses,4,infraestrutura_urbana,IU_01,indireta,alerta,ETE de Hortolandia acumulou 18 multas da Cetes...,Hortolandia,Hortolandia,local,indicador,Sabesp preve R$ 28 mi para modernizacao e estu...,nao_aplicavel,nao_aplicavel,negativo,saneamento
1,Tribuna Liberal,2026-03-04,Pai sequestra filha de 2 anos - Jardim Amanda,9,capital_humano,NaN,contextual,alerta,Pai sequestra filha de 2 anos no Jardim Amanda...,Hortolandia,Hortolandia,local,problema,Evento iniciou na Rua Washington Luiz no Jardi...,351,alto,negativo,seguranca
2,Tribuna Liberal,2026-03-04,Regularizacao fundiaria e habitacao - reuniao ...,8,infraestrutura_urbana,IU_01,indireta,media,Prefeito reune-se com secretario estadual de H...,Hortolandia,Hortolandia,local,politica_publica,Bairros envolvidos: Jd. Aline Santiago Guedes ...,nao_aplicavel,nao_aplicavel,positivo,habitacao
3,Tribuna Liberal,2026-03-04,Obra de drenagem - Jardim Novo Angulo,8,infraestrutura_urbana,IU_01,indireta,media,Maquinas iniciam obras de reparo de erosao na ...,Hortolandia,Hortolandia,local,politica_publica,Obra executada como contrapartida de empreendi...,307,medio,positivo,infraestrutura
4,Tribuna Liberal,2026-03-04,Servidores municipais pedem vale-alimentacao n...,4,renda_trabalho,NaN,contextual,baixa,Grupo de servidores municipais vai a Camara de...,Hortolandia,Hortolandia,local,problema,Mobilizacao apos suspensao da cesta de Natal; ...,nao_aplicavel,nao_aplicavel,negativo,economia

In [4]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-05,MCMV - 400 unidades habitacionais em construca...,5,infraestrutura_urbana,IU_01,indireta,alta,Obras de 400 unidades habitacionais do MCMV em...,Hortolandia,Hortolandia,local,politica_publica,Jardim Amanda e loteamento com maior concentra...,351,alto,positivo,habitacao
1,Tribuna Liberal,2026-03-05,Briga com dois baleados - Jardim Amanda,8,capital_humano,NaN,contextual,alerta,Briga na madrugada no Jardim Amanda resulta em...,Hortolandia,Hortolandia,local,problema,Evento ocorreu na residencia de ex-companheira...,351,alto,negativo,seguranca
2,Tribuna Liberal,2026-03-05,Painel violencia contra mulher - Camara Municipal,5,capital_humano,NaN,indireta,alta,Camara Municipal realiza painel Combater a Vio...,Hortolandia,Hortolandia,local,politica_publica,Maria dos Anjos compoe o painel; iniciativa do...,366,medio,positivo,assistencia_social
3,Tribuna Liberal,2026-03-05,Interdicao de ponte - Jardim Ricardo,6,infraestrutura_urbana,IU_01,indireta,media,Prefeitura interdita preventivamente ponte na ...,Hortolandia,Hortolandia,local,problema,Problema agravado por vazao de aguas pluviais ...,93,alto,negativo,infraestrutura
4,Tribuna Liberal,2026-03-05,Visita do prefeito a Dell Technologies,5,renda_trabalho,NaN,contextual,baixa,Prefeito Zeze Gomes visita Dell Technologies c...,Hortolandia,Hortolandia,local,politica_publica,Dell instalada em Hortolandia desde 2007; mais...,nao_aplicavel,nao_aplicavel,positivo,economia

In [5]:
import pandas as pd

teste = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv"

df = pd.read_csv(teste)

df.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-06,Auxilio-refeicao - projeto vai a Camara,5,renda_trabalho,RT_01,indireta,media,Prefeitura anuncia estudos para enviar PL que ...,Hortolandia,Hortolandia,local,politica_publica,Projeto em fase de estudos; impacto potencial ...,nao_aplicavel,nao_aplicavel,positivo,institucional
1,Tribuna Liberal,2026-03-06,MCMV - 576 documentacoes entregues - Jardim Am...,5,infraestrutura_urbana,IU_01,indireta,alta,Mais da metade dos 1000 pre-selecionados ja en...,Hortolandia,Hortolandia,local,politica_publica,520 familias serao selecionadas (400 titulares...,351,alto,positivo,habitacao
2,Tribuna Liberal,2026-03-06,Fatec Hortolandia - encontro com empresarios,10,renda_trabalho,NaN,contextual,baixa,Prefeitura promove encontro com representantes...,Hortolandia,Hortolandia,local,politica_publica,Fatec ainda nao implantada; reuniao de diagnos...,nao_aplicavel,nao_aplicavel,positivo,economia
3,Tribuna Liberal,2026-03-06,Prisao preventiva - pai filha Jardim Amanda,6,capital_humano,NaN,contextual,alerta,Justica decreta prisao preventiva do pai acusa...,Hortolandia,Hortolandia,local,problema,Caso investigado pela DDM de Sumare; delegada ...,351,alto,negativo,seguranca

In [6]:
import pandas as pd

arquivos = [
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv",
    r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv"
]

dfs = [pd.read_csv(f) for f in arquivos]

df_total = pd.concat(dfs, ignore_index=True)

df_total.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,93,alto,negativo,infraestrutura
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,86,alto,negativo,infraestrutura
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,333,alto,negativo,infraestrutura
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,317,alto,negativo,infraestrutura
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,6,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,Sem limite de vagas - funciona como Banco de T...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social

O r significa: “não interprete as barras como código” e simples e tab funicona "C:/Users/ailto/Atlas-Social-de-Hortolandia/00_governanca/series_jornalisticas/2026_03_01_tribuna_liberal.csv"                                                                          
📍 O que é ignore_index=True

Quando você usa:

df_total = pd.concat(dfs, ignore_index=True)

você está dizendo ao pandas:

“Ignore os índices originais de cada DataFrame e crie um novo índice contínuo.”

🧠 Vamos entender com calma
🔹 Cada CSV tem seu próprio índice

Quando você lê um arquivo:

df = pd.read_csv(...)

ele vem assim:

0
1
2
3

Agora imagine que você tem 5 arquivos.

Cada um deles começa do zero:

Arquivo 1 → 0,1,2,3
Arquivo 2 → 0,1,2
Arquivo 3 → 0,1,2,3,4
🔴 Se você NÃO usar ignore_index
df_total = pd.concat(dfs)

Resultado:

0
1
2
3
0
1
2
0
1
2
3
4

👉 Índices repetidos
👉 Bagunça lógica
👉 Pode dar erro em análises futuras

🟢 Se você usar ignore_index=True
df_total = pd.concat(dfs, ignore_index=True)

Resultado:

0
1
2
3
4
5
6
7
8
9
10
...

👉 índice único
👉 contínuo
👉 limpo para análise

📊 Interpretação conceitual (importante para o seu projeto)

No seu caso:

Você está criando um dataset consolidado de notícias.

Então faz total sentido dizer:

“Cada linha agora é um evento único no tempo — não importa de qual arquivo veio.”

Logo:

✔️ índice novo = identidade do dataset consolidado
❌ índice antigo = identidade do arquivo original (não interessa mais)

⚠️ Quando NÃO usar ignore_index

Você NÃO usaria se:

o índice tem significado (ex: ID único)
você quer rastrear origem linha a linha pelo índice

Mas no seu caso:

👉 você já tem:

data
fonte
item

Então o índice não tem valor analítico.

🧭 Tradução prática
Situação	Usar ignore_index
Juntar vários CSVs iguais	✅ Sim
Criar base única de análise	✅ Sim
Índice tem significado (ID)	❌ Não
📌 Em uma frase

ignore_index=True transforma vários arquivos separados em uma única tabela contínua e coerente para análise.

In [7]:
import pandas as pd
import glob

pasta = r"C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas"

arquivos = glob.glob(pasta + r"\2026_*_*_tribuna_liberal.csv")

arquivos

['C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_04_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_06_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_14_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_18_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_21_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_24_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_25_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_26_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_27_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_28_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_29_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_03_31_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_01_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_02_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_03_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_05_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_07_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_08_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_09_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_10_tribuna_liberal.csv',
 'C:\\Users\\ailto\\Atlas-Social-de-Hortolandia\\00_governanca\\series_jornalisticas\\2026_04_11_tribuna_liberal.csv']

In [8]:
for f in arquivos:
    try:
        df = pd.read_csv(f)
        print(f, "->", list(df.columns))
    except Exception as e:
        print(f, "-> ERRO:", e)

C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_04_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_05_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_06_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_14_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_18_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'nivel_criticidade', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_21_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_24_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_25_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_26_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_27_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_28_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_29_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_03_31_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_01_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_02_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_03_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_05_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_07_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_08_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_09_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_10_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']
C:\Users\ailto\Atlas-Social-de-Hortolandia\00_governanca\series_jornalisticas\2026_04_11_tribuna_liberal.csv -> ['fonte', 'data', 'item', 'pagina', 'dimensao_ivs', 'codigo_variavel', 'tipo_relacao_variavel', 'resumo', 'origem', 'municipio_impactado', 'tipo_abrangencia', 'tipo_evento', 'gravidade', 'observacao', 'cod_loteamento', 'nivel_confianca_loteamento', 'polaridade_evento', 'tipo_origem_evento']

In [9]:
dfs = []

for f in arquivos:
    df = pd.read_csv(f)
    df["arquivo_origem"] = f
    dfs.append(df)

df_total = pd.concat(dfs, ignore_index=True)

df_total.head()

,fonte,data,item,pagina,dimensao_ivs,codigo_variavel,tipo_relacao_variavel,nivel_criticidade,resumo,origem,municipio_impactado,tipo_abrangencia,tipo_evento,observacao,cod_loteamento,nivel_confianca_loteamento,polaridade_evento,tipo_origem_evento,arquivo_origem,gravidade
0,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Ricardo,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,93,alto,negativo,infraestrutura,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
1,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Sumarez...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,86,alto,negativo,infraestrutura,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
2,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Adelaide,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,333,alto,negativo,infraestrutura,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
3,Tribuna Liberal,2026-03-01,Familias atingidas pela chuva - Jardim Santa C...,9,infraestrutura_urbana,IU_01,direta,alta,Chuva de 82mm na madrugada de 26/02 inunda cas...,Hortolandia,Hortolandia,local,problema,Defesa Civil fez triagem e acionou secretarias...,317,alto,negativo,infraestrutura,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN
4,Tribuna Liberal,2026-03-01,Programa Acerte abre cadastro - Costura Indust...,6,renda_trabalho,RT_02,indireta,media,Prefeitura abre cadastro para Programa Acerte ...,Hortolandia,Hortolandia,local,politica_publica,Sem limite de vagas - funciona como Banco de T...,nao_aplicavel,nao_aplicavel,positivo,assistencia_social,C:\Users\ailto\Atlas-Social-de-Hortolandia\00_...,NaN

In [10]:
df_total['dimensao_ivs'].value_counts()

dimensao_ivs
capital_humano           38
infraestrutura_urbana    28
renda_trabalho           16
multidimensional          8
governanca                5
SMIDS_EXT                 2
Name: count, dtype: int64

In [11]:
df_total['polaridade_evento'].value_counts()

polaridade_evento
positivo    55
negativo    42
Name: count, dtype: int64

In [12]:
df_total['nivel_criticidade'].value_counts()

nivel_criticidade
media     13
alta      11
baixa      5
alerta     4
Name: count, dtype: int64

In [13]:
df_total['tipo_evento'].value_counts()

tipo_evento
politica_publica        37
problema                23
infraestrutura          13
violencia                8
indicador                4
seguranca                4
institucional            3
caso_individual          1
vulnerabilidade          1
economia                 1
pressao_orcamentaria     1
governanca               1
Name: count, dtype: int64

In [15]:
mapa_loteamentos = {
    "351": "Jardim Amanda",
    "93": "Jardim Ricardo",
    "86": "Jardim Sumarezinho",
    "333": "Jardim Adelaide"
}

In [16]:
df_total["nome_loteamento"] = df_total["cod_loteamento"].map(mapa_loteamentos)

In [17]:
df_total["nome_loteamento"].value_counts()

nome_loteamento
Jardim Amanda         11
Jardim Ricardo         2
Jardim Sumarezinho     1
Jardim Adelaide        1
Name: count, dtype: int64

In [14]:
df_total[df_total['cod_loteamento'] != 'nao_aplicavel']['cod_loteamento'].value_counts()

cod_loteamento
351                       11
66                         3
93                         2
57                         2
317                        2
sem_codigo_monte_sinai     2
63                         2
342                        1
349                        1
370                        1
341                        1
nao_identificado           1
457                        1
318                        1
86                         1
398                        1
457                        1
319                        1
366                        1
Chacaras 2000              1
307                        1
383                        1
333                        1
331                        1
Name: count, dtype: int64

In [18]:
df_filtrado = df_total[
    ~df_total["dimensao_ivs"].isin(["governanca", "SMIDS_EXT"])
]